### ISSUE TITLE
Handover from QtXlsxWriter

### ISSUE THREAD

**Issue by VSRonin** [QtExcel/QXlsx#35]
Hi guys, I'm currently maintaining the fork of QtXlsxWriter that is most "popular" to keep it working. Unfortunately however I have not been able to dedicate to it the time I wanted to. Would you be interested in taking over the ownership of that repo and either merge or disband it once you are comfortable there are no further gaps between QXlsx and the old QtXlsxWriter?

**Comment by j2doll** [comment]
Dear @VSRobin.
Thank you for your good advice and recommendation.

 First, QtXlsxWriter and QXlsx are difficult to merge.  And I want to make QXlsx a new version using the XSD schema in the future.  Maybe I will no longer use QtXlsxWriter-based code.

 Second, if you want, I can support the updating code of your forked QtXlsxWriter repository.  Alternatively, I can escalate to the QtExcel team's store and then invite you to join the team.
 Of course, if you delegate authority of the repository to me, I will configure it as a team repository for everyone, not my personal repository.

 The reason I am collecting various Qt libraries that support various Excel development on the QtExcel team is to find an efficient way to solve various cases.

**Comment by VSRonin** [comment]
Thanks @j2doll,
I would be happy to relinquish control to the QtExcel team as it would be more practical to add people at a later stage. I do realise it's is currently a one man band and I'd be happy to be part of it but, as I mentioned I was not able to give it enough support in the past and I only see my availability declining in the future.
My core question is: would you be interested in maintaining that repository? If it's a burden I'll find some other solution.

**Comment by j2doll** [comment]
I am interested in creating a new library rather than maintaining the repository.  

There is a limit to the way you do not use the ecma 376 schema directly.  
I think that hard-coded methods without using a schema have limitations in determining the specific goals of the development goals and the methods for the unit tests.

And if you want to be invited to the QtExcel team, I can invite you. 
Currently there are only two team members, but it seems to be advantageous to work with a team. 
Of course, if you create a team,  I can help.  May the force be with you!

**Comment by VSRonin** [comment]
> There is a limit to the way you do not use the ecma 376 schema directly.

Indeed. When I forked the original project and started working on it I quickly realised what a huge problem this was and it's also the main reason why the library didn't implement anything "cool" since
